
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka-d3
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        ports:
        - name: kafka
          containerPort: 9092
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.kafka-d3.svc.cluster.local:9092"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: JMX_PORT
          value: "9099"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka-d3
spec:
  ports:
  - name: kafka
    # targetPort: 9092
    protocol: TCP
    port: 9092
  - name: jmx
    # targetPort: 9092
    protocol: TCP
    port: 9099
  selector:
    app: kafka
  type: ClusterIP