---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka-d3
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-exporter
  template:
    metadata:
      labels:
        task: kafka-d3
        k8s-app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        ports:
        - containerPort: 9308
        image: danielqsj/kafka-exporter 
        args: ["--kafka.server=kafka:9092", "--kafka.version=2.4.0"] 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: kafka-exporter
  name: kafka-exporter
  namespace: kafka-d3
spec:
  ports:
  - port: 9308
    targetPort: 9308
  selector:
    k8s-app: kafka-exporter
