---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka-d3
  labels:
    k8s-app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
        k8s-app: zookeeper
    spec:
      containers:
      - name: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        - containerPort: 8080 
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        image: bitnami/zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka-d3
spec:
  selector:
    k8s-app: zookeeper
  ports:
  - name: client-port
    port: 2181
    targetPort: 2181
  - name: follower-port
    port: 2888
    targetPort: 2888
  - name: election-port
    port: 3888
    targetPort: 3888
  - name: admin-server
    port: 8080
    targetPort: 8080
